export const GET_ERRORS = "GET_ERRORS";
export const GET_PERSONS = "GET_PERSONS";
export const GET_PERSON = "GET_PERSON";
export const GET_BOOKS = "GET_BOOKS";
export const GET_BOOK = "GET_BOOK";
export const GET_CATEGORIES = "GET_CATEGORIES";

export const GET_USER_REQUESTS = "GET_USER_REQUESTS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_REVIEWS = "GET_REVIEWS";
export const GET_USER = "GET_USER";

export const GET_USER_TRANSACTIONS = "GET_USER_TRANSACTIONS";
export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_ALL_BOOK_TRANSACTIONS = "GET_ALL_BOOK_TRANSACTIONS";

export const GET_CART_TOTAL = "GET_CART_TOTAL"
export const GET_CART_ITEMS = "GET_CART_ITEMS"
